-- UncappedLootFeedData -- the lookup layer over the baked item table
-- (UncappedLootFeedItemData.lua, generated by tools/Generate-LootItemDB.py).
--
-- WHY THIS LAYER EXISTS
--   The launcher wipes Cache/WDB every launch, so GetItemInfo returns nil for
--   everything until the server answers a per-item query. That is fine for a
--   feed row -- the item LINK in the chat message already carries the server's
--   own name and quality colour -- but it is fatal for the watchlist browser,
--   which has to let you search for an item you have never seen this session.
--   The baked table is what makes that search possible at all.
--
-- WHAT IS NOT IN THE BAKED TABLE: ICONS
--   GetItemIcon reads the client's own Item.dbc, NOT the WDB cache, so it
--   answers for items the player has never seen -- the same thing
--   UncappedTransmog.lua relies on. Measured: 18,566 of this realm's 18,567
--   droppable items are in the client's Item.dbc, so baking icon paths would be
--   ~600 KB restating what the client already knows. Only the exceptions (this
--   realm's custom items) ship, in UncappedLootFeedIcons.
--
-- WHY THE ROWS ARE STRINGS AND WHY NOTHING BUILDS AN [id] = name TABLE
--   Measured in Lua 5.1 on the 25,459-row set:
--       packed strings, flat array  ->  2.52 MB, 69 ms to load
--       same data as nested tables  ->  8.15 MB, 102 ms to load
--   So rows stay strings, and an id lookup BINARY SEARCHES the array (it is
--   generated sorted by entry) rather than building an index. 0.005 ms per
--   lookup measured, and no extra memory at all.

local Data = {}
_G.UncappedLootFeedData = Data

local ITEMS   -- resolved lazily: the generated file may load after this one
local COUNT = 0

local function Rows()
    if ITEMS == nil then
        ITEMS = _G.UncappedLootFeedItems or false
        COUNT = ITEMS and #ITEMS or 0
    end
    return ITEMS
end

function Data.IsReady()
    return Rows() and COUNT > 0
end

function Data.Count()
    Rows()
    return COUNT
end

-- ---------------------------------------------------------------------------
-- id -> name / quality
-- ---------------------------------------------------------------------------
-- Binary search. The generator emits rows sorted by entry ascending; if that
-- ever stops being true this quietly starts missing items, so the ordering is
-- asserted in the generator rather than re-sorted here (25k sorts at load would
-- cost more than the search saves).
local function FindRow(id)
    local items = Rows()
    if not items then return nil end

    local lo, hi = 1, COUNT
    while lo <= hi do
        local mid = math.floor((lo + hi) / 2)
        local row = items[mid]
        local entry = tonumber(row:match("^(%d+):"))
        if entry == id then
            return row
        elseif entry < id then
            lo = mid + 1
        else
            hi = mid - 1
        end
    end
    return nil
end

local infoCache = {}   -- [id] = { name, quality } -- memoised, tiny in practice

-- Returns name, quality for a baked item, or nil when it is not in the table
-- (an item that cannot drop, or one added since the table was generated).
function Data.Get(id)
    id = tonumber(id)
    if not id then return nil end

    local hit = infoCache[id]
    if hit then return hit[1], hit[2] end

    local row = FindRow(id)
    if not row then return nil end

    local q, name = row:match("^%d+:(%d+):(.*)$")
    if not name then return nil end

    q = tonumber(q) or 1
    infoCache[id] = { name, q }
    return name, q
end

-- Best available name, in order of trustworthiness: the live client cache
-- (which is the server's own answer), then the baked table, then a bare id so
-- the caller never has to handle nil.
function Data.NameFor(id)
    local live = GetItemInfo(id)
    if live then return live end
    local baked = Data.Get(id)
    if baked then return baked end
    return "item " .. tostring(id)
end

function Data.QualityFor(id)
    local live = select(3, GetItemInfo(id))
    if live then return live end
    local _, q = Data.Get(id)
    return q
end

-- ---------------------------------------------------------------------------
-- Colours
-- ---------------------------------------------------------------------------
-- Fallback mirrors ITEM_QUALITY_COLORS, which exists on this client but is
-- guarded anyway so a missing global cannot break a row.
local QCOLOR = {
    [0] = { r = 0.62, g = 0.62, b = 0.62 },
    [1] = { r = 1.00, g = 1.00, b = 1.00 },
    [2] = { r = 0.12, g = 1.00, b = 0.00 },
    [3] = { r = 0.00, g = 0.44, b = 0.87 },
    [4] = { r = 0.64, g = 0.21, b = 0.93 },
    [5] = { r = 1.00, g = 0.50, b = 0.00 },
    [6] = { r = 0.90, g = 0.80, b = 0.50 },
    [7] = { r = 0.90, g = 0.80, b = 0.50 },
}

function Data.QualityColor(q)
    q = tonumber(q)
    local c = (q and ITEM_QUALITY_COLORS and ITEM_QUALITY_COLORS[q]) or QCOLOR[q or 1] or QCOLOR[1]
    return c.r, c.g, c.b
end

function Data.QualityHex(q)
    local r, g, b = Data.QualityColor(q)
    return string.format("|cff%02x%02x%02x", r * 255, g * 255, b * 255)
end

function Data.ColoredName(id, name, q)
    name = name or Data.NameFor(id)
    q = q or Data.QualityFor(id)
    return Data.QualityHex(q) .. name .. "|r"
end

-- ---------------------------------------------------------------------------
-- Icons
-- ---------------------------------------------------------------------------
local PLACEHOLDER = "Interface\\Icons\\INV_Misc_QuestionMark"

-- One tooltip used purely to nudge the client into caching an item -- setting a
-- hyperlink on it makes the client ask the server, which is what fills
-- GetItemInfo in later. Never shown.
local scanTip = CreateFrame("GameTooltip", "UncappedLootFeedScanTip", nil, "GameTooltipTemplate")
scanTip:SetOwner(UIParent, "ANCHOR_NONE")

local queried = {}

-- Cheap path first (client DBC, always available), then this realm's custom
-- items, then the live cache, then a one-shot query + placeholder. Without the
-- `queried` guard every repaint of a list of uncached items would fire a fresh
-- query storm at the server.
function Data.IconFor(id)
    id = tonumber(id)
    if not id then return PLACEHOLDER end

    if GetItemIcon then
        local tex = GetItemIcon(id)
        if tex then return tex end
    end

    local override = _G.UncappedLootFeedIcons and _G.UncappedLootFeedIcons[id]
    if override then return override end

    local tex = select(10, GetItemInfo(id))
    if tex then return tex end

    if not queried[id] then
        queried[id] = true
        scanTip:SetHyperlink("item:" .. id)
    end
    return PLACEHOLDER
end

-- ---------------------------------------------------------------------------
-- Search
-- ---------------------------------------------------------------------------
-- Case-insensitive without a lowercase shadow copy of the table: the (short)
-- query becomes a pattern where every letter is a two-character class, so the
-- match still runs entirely in C and costs no extra memory. A lowercased second
-- array would have cost another ~2.5 MB, which is the whole thing again.
local function ToPattern(query)
    local pat = query:gsub("[%^%$%(%)%%%.%[%]%*%+%-%?]", "%%%0")
    pat = pat:gsub("%a", function(c) return "[" .. c:lower() .. c:upper() .. "]" end)
    return pat
end

local MIN_QUERY = 2
local DEFAULT_LIMIT = 200

-- Blizzard shipped a lot of dead duplicates that share a real item's name with a
-- marker glued on -- "Thunderfury, Blessed Blade of the Windseeker DEPRECATED"
-- sits right next to the real 19019. These are RANKED LAST, never filtered out:
-- an item that is in a loot table can genuinely drop, so hiding it from the
-- browser would be a real loss, whereas letting it outrank the item the player
-- obviously meant is just wrong. Markers only, no word-boundary games needed --
-- this decides sort order, not membership, so a false positive costs nothing.
local JUNK = { "deprecated", "%(old%)", "unused", "obsolete", "placeholder", "%[ph%]", "%(dev%)", "do not use" }

local function IsJunk(lname)
    for i = 1, #JUNK do
        if lname:find(JUNK[i]) then return true end
    end
    return false
end

-- Returns an array of { id =, name =, q = }, capped at `limit`.
--
-- A purely numeric query is treated as an item id rather than as text: that is
-- the one case where the player unambiguously means one specific item, and it
-- also stops "12" from matching the id digits of thousands of rows.
function Data.Search(query, limit)
    local out = {}
    local items = Rows()
    if not items then return out end

    query = (query or ""):gsub("^%s+", ""):gsub("%s+$", "")
    if query == "" then return out end
    limit = limit or DEFAULT_LIMIT

    local asId = tonumber(query:match("^%d+$") or "")
    if asId then
        local name, q = Data.Get(asId)
        if name then
            out[1] = { id = asId, name = name, q = q }
        elseif GetItemInfo(asId) then
            -- Not in the baked table (custom or newer than the table), but the
            -- client knows it -- still a legitimate watch target.
            out[1] = { id = asId, name = GetItemInfo(asId), q = select(3, GetItemInfo(asId)) }
        end
        return out
    end

    if query:len() < MIN_QUERY then return out end

    local pat = ToPattern(query)
    local plain = query:lower()

    for i = 1, COUNT do
        local row = items[i]
        -- Prefilter on the whole packed row (one C-side find), then confirm
        -- against the NAME only, so a query can never match the id or quality
        -- digits that share the string.
        if row:find(pat) then
            local id, q, name = row:match("^(%d+):(%d+):(.*)$")
            if name then
                local lname = name:lower()
                if lname:find(plain, 1, true) then
                    out[#out + 1] = {
                        id = tonumber(id), name = name, q = tonumber(q),
                        exact = (lname == plain),
                        prefix = (lname:find(plain, 1, true) == 1),
                        junk = IsJunk(lname),
                    }
                    if #out >= limit then break end
                end
            end
        end
    end

    -- Exact name first, then names that START with what was typed (almost
    -- always what was meant), then live items ahead of dead duplicates, then
    -- alphabetical. Without the junk rank, "Thunderfury" resolves to the
    -- DEPRECATED copy, which is a lower entry id and so is found first.
    table.sort(out, function(a, b)
        if a.exact ~= b.exact then return a.exact end
        if a.prefix ~= b.prefix then return a.prefix end
        if a.junk ~= b.junk then return b.junk end
        if a.name ~= b.name then return a.name < b.name end
        return a.id < b.id
    end)

    return out
end
