using System.Text.Json.Serialization;

namespace Uncapped.Model;

/// <summary>
/// What a legitimate Uncapped client is made of, below the files we publish ourselves.
///
/// manifest.json describes our ~480 payload files and nothing else, so for the other 16 GB
/// the launcher had no opinion at all: a truncated common.MPQ, or a patch-enUS-X.MPQ carried
/// over from another server, was indistinguishable from a healthy install. It only became
/// visible at the login screen, as version_gate.lua kicking the player 25 seconds in — which
/// reads as "the server is broken", not "your client is".
///
/// This is the other half of the picture. Between the two, every file under a checked root is
/// either accounted for or, by definition, not part of an Uncapped release.
///
/// Generated by tools/New-Baseline.ps1 and served from the patch host rather than compiled in,
/// so the scope can be corrected without cutting a launcher release — which matters, because
/// the failure mode of getting it wrong is telling a player with a perfectly good client that
/// it is not legitimate.
/// </summary>
public sealed class Baseline
{
    [JsonPropertyName("baselineVersion")] public int BaselineVersion { get; set; } = 1;
    [JsonPropertyName("generated")] public string? Generated { get; set; }

    /// <summary>The client build the hashes were taken from. Part of every served filename.</summary>
    [JsonPropertyName("clientBuild")] public string ClientBuild { get; set; } = "";

    /// <summary>
    /// The language the hashes describe. A client in another language has different bytes in
    /// Data\&lt;locale&gt;\, so those entries are skipped rather than failed — a legitimate deDE
    /// install must not be called tampered with.
    /// </summary>
    [JsonPropertyName("locale")] public string Locale { get; set; } = "enUS";

    /// <summary>Folders walked recursively, install-root-relative.</summary>
    [JsonPropertyName("checkedRoots")] public List<string> CheckedRoots { get; set; } = new();

    /// <summary>Extensions of loose files in the install root that are checked. Non-recursive.</summary>
    [JsonPropertyName("checkRootFiles")] public List<string> CheckRootFiles { get; set; } = new();

    /// <summary>
    /// Top-level folders never descended into: Cache and WTF on the owner's instruction, plus
    /// Logs, Errors and Screenshots, which are the same kind of player-generated data. Interface
    /// is here too — our addons are covered by the manifest, and everyone else's are the
    /// player's business, not evidence of anything.
    /// </summary>
    [JsonPropertyName("skipRoots")] public List<string> SkipRoots { get; set; } = new();

    /// <summary>
    /// Filenames that may be present without being foreign, because the launcher itself puts
    /// them there, renames them, or removes them.
    /// </summary>
    [JsonPropertyName("toleratedNames")] public List<string> ToleratedNames { get; set; } = new();

    /// <summary>Glob patterns for working files — retired patches, backups, logs.</summary>
    [JsonPropertyName("toleratedPatterns")] public List<string> ToleratedPatterns { get; set; } = new();

    [JsonPropertyName("files")] public List<BaselineFile> Files { get; set; } = new();
}

public sealed class BaselineFile
{
    /// <summary>Install-root-relative, forward slashes, as generated against the baseline locale.</summary>
    [JsonPropertyName("path")] public string Path { get; set; } = "";

    [JsonPropertyName("sha256")] public string Sha256 { get; set; } = "";
    [JsonPropertyName("size")] public long Size { get; set; }

    /// <summary>
    /// Whether the client needs this file to run.
    ///
    /// Only required files block PLAY or get hosted for repair. The rest — Credits.html,
    /// Documentation\, the .url shortcuts — are verified when they match and ignored when they
    /// do not, because there are two legitimate ways to obtain the client (the ChromieCraft
    /// torrent and the Internet Archive zips) and they need not agree on that long tail. A
    /// cosmetic difference between two genuine installs must not read as tampering.
    /// </summary>
    [JsonPropertyName("required")] public bool Required { get; set; }

    /// <summary>True for files under Data\&lt;locale&gt;\, which only a matching client can be checked against.</summary>
    [JsonPropertyName("locale")] public bool Locale { get; set; }

    /// <summary>Where to fetch a replacement. Present on required files only.</summary>
    [JsonPropertyName("url")] public string? Url { get; set; }

    /// <summary>The filename the patch host serves it under. Diagnostic; the URL is what is used.</summary>
    [JsonPropertyName("served")] public string? Served { get; set; }
}
