-- UncappedUIKit pattern index -- GENERATED, do not hand-edit.
--
-- Built from the .tga files actually present in Assets/Patterns, so a pattern
-- cannot appear in the Appearance gallery without shipping, and cannot ship
-- without appearing. Regenerate with tools mklist.py after adding art.

local UncappedUIKit = _G.UncappedUIKit
if not UncappedUIKit then return end

UncappedUIKit.PATTERNS = {
    { key = "Cloud01", label = "Billow", family = "Nebula" },
    { key = "Cloud02", label = "Billow II", family = "Nebula" },
    { key = "Cloud03", label = "Drift", family = "Nebula" },
    { key = "Cloud04", label = "Drift II", family = "Nebula" },
    { key = "Cloud05", label = "Veil", family = "Nebula" },
    { key = "Cloud06", label = "Veil II", family = "Nebula" },
    { key = "Cloud07", label = "Bloom", family = "Nebula" },
    { key = "Cloud08", label = "Bloom II", family = "Nebula" },
    { key = "Cloud09", label = "Wisp", family = "Nebula" },
    { key = "Cloud10", label = "Wisp II", family = "Nebula" },
    { key = "Cloud11", label = "Filament", family = "Nebula" },
    { key = "Cloud12", label = "Filament II", family = "Nebula" },
    { key = "Cloud13", label = "Thread", family = "Nebula" },
    { key = "Cloud14", label = "Thread II", family = "Nebula" },
    { key = "Cloud15", label = "Mist", family = "Nebula" },
    { key = "Cloud16", label = "Mist II", family = "Nebula" },
    { key = "Cloud17", label = "Turbulence", family = "Nebula" },
    { key = "Cloud18", label = "Turbulence II", family = "Nebula" },
    { key = "Cloud19", label = "Ember Cloud", family = "Nebula" },
    { key = "Cloud20", label = "Ember Cloud II", family = "Nebula" },
    { key = "Cloud21", label = "Cirrus", family = "Nebula" },
    { key = "Cloud22", label = "Cirrus II", family = "Nebula" },
    { key = "Cloud23", label = "Deep", family = "Nebula" },
    { key = "Cloud24", label = "Deep II", family = "Nebula" },
    { key = "Star01", label = "Scattered", family = "Stars" },
    { key = "Star02", label = "Deep Field", family = "Stars" },
    { key = "Star03", label = "Sparse", family = "Stars" },
    { key = "Star04", label = "Dust", family = "Stars" },
    { key = "Star05", label = "Bright", family = "Stars" },
    { key = "Arcane01", label = "Ley Lines", family = "Arcane" },
    { key = "Arcane02", label = "Ley Convergence", family = "Arcane" },
    { key = "Arcane03", label = "Interference Veil", family = "Arcane" },
    { key = "Arcane04", label = "Moire Bloom", family = "Arcane" },
    { key = "Arcane05", label = "Rune Lattice", family = "Arcane" },
    { key = "Arcane06", label = "Sigil Rings", family = "Arcane" },
    { key = "Arcane07", label = "Mana Weave", family = "Arcane" },
    { key = "Arcane08", label = "Astral Field", family = "Arcane" },
    { key = "Arcane09", label = "Runic Circuit", family = "Arcane" },
    { key = "Arcane10", label = "Astral Drift", family = "Arcane" },
    { key = "Radiance01", label = "Dawnlight", family = "Holy" },
    { key = "Radiance02", label = "Aurora Veil", family = "Holy" },
    { key = "Radiance03", label = "Sanctum", family = "Holy" },
    { key = "Radiance04", label = "Vespers", family = "Holy" },
    { key = "Radiance05", label = "Benediction", family = "Holy" },
    { key = "Radiance06", label = "Gilded Filigree", family = "Holy" },
    { key = "Radiance07", label = "Motes", family = "Holy" },
    { key = "Radiance08", label = "Sanctuary", family = "Holy" },
    { key = "Radiance09", label = "Gloria", family = "Holy" },
    { key = "Radiance10", label = "Ascension", family = "Holy" },
    { key = "Ice01", label = "Rime", family = "Frost" },
    { key = "Ice02", label = "Glacier", family = "Frost" },
    { key = "Ice03", label = "Hoarfrost", family = "Frost" },
    { key = "Ice04", label = "Shatter", family = "Frost" },
    { key = "Ice05", label = "Crevasse", family = "Frost" },
    { key = "Ice06", label = "Icicle", family = "Frost" },
    { key = "Ice07", label = "Deep Freeze", family = "Frost" },
    { key = "Ice08", label = "Permafrost", family = "Frost" },
    { key = "Ice09", label = "Snowveil", family = "Frost" },
    { key = "Ice10", label = "Black Ice", family = "Frost" },
    { key = "Storm01", label = "Forked", family = "Storm" },
    { key = "Storm02", label = "Chainforge", family = "Storm" },
    { key = "Storm03", label = "Splinter", family = "Storm" },
    { key = "Storm04", label = "Thunderhead", family = "Storm" },
    { key = "Storm05", label = "Static", family = "Storm" },
    { key = "Storm06", label = "Squall", family = "Storm" },
    { key = "Storm07", label = "Discharge", family = "Storm" },
    { key = "Storm08", label = "Fissure", family = "Storm" },
    { key = "Storm09", label = "Voltaic", family = "Storm" },
    { key = "Storm10", label = "Tempest", family = "Storm" },
    { key = "Grove01", label = "Bramble Thicket", family = "Nature" },
    { key = "Grove02", label = "Canopy Filter", family = "Nature" },
    { key = "Grove03", label = "Rootwork", family = "Nature" },
    { key = "Grove04", label = "Lichen Crust", family = "Nature" },
    { key = "Grove05", label = "Leaf Venation", family = "Nature" },
    { key = "Grove06", label = "Verdant Tangle", family = "Nature" },
    { key = "Grove07", label = "Mossbed", family = "Nature" },
    { key = "Grove08", label = "Deadwood Grain", family = "Nature" },
    { key = "Grove09", label = "Fern Lattice", family = "Nature" },
    { key = "Grove10", label = "Undergrowth", family = "Nature" },
    { key = "Ember01", label = "Cinder", family = "Fire" },
    { key = "Ember02", label = "Wildfire", family = "Fire" },
    { key = "Ember03", label = "Smoulder", family = "Fire" },
    { key = "Ember04", label = "Firestorm", family = "Fire" },
    { key = "Ember05", label = "Cracked Coals", family = "Fire" },
    { key = "Ember06", label = "Forge Heat", family = "Fire" },
    { key = "Ember07", label = "Ashfall", family = "Fire" },
    { key = "Ember08", label = "Scorch", family = "Fire" },
    { key = "Ember09", label = "Kindling", family = "Fire" },
    { key = "Ember10", label = "Blaze Core", family = "Fire" },
    { key = "Blood01", label = "Clot", family = "Blood" },
    { key = "Blood02", label = "Arterial", family = "Blood" },
    { key = "Blood03", label = "Spatter", family = "Blood" },
    { key = "Blood04", label = "Sanguine", family = "Blood" },
    { key = "Blood05", label = "Ichor", family = "Blood" },
    { key = "Blood06", label = "Congeal", family = "Blood" },
    { key = "Blood07", label = "Capillary", family = "Blood" },
    { key = "Blood08", label = "Spray", family = "Blood" },
    { key = "Blood09", label = "Weep", family = "Blood" },
    { key = "Blood10", label = "Gore", family = "Blood" },
    { key = "Toxin01", label = "Blight", family = "Poison" },
    { key = "Toxin02", label = "Miasma", family = "Poison" },
    { key = "Toxin03", label = "Spore Bloom", family = "Poison" },
    { key = "Toxin04", label = "Corrosion", family = "Poison" },
    { key = "Toxin05", label = "Membrane", family = "Poison" },
    { key = "Toxin06", label = "Bile", family = "Poison" },
    { key = "Toxin07", label = "Pustule", family = "Poison" },
    { key = "Toxin08", label = "Ichor Web", family = "Poison" },
    { key = "Toxin09", label = "Toxic Froth", family = "Poison" },
    { key = "Toxin10", label = "Caustic Fog", family = "Poison" },
    { key = "Necro01", label = "Ossuary", family = "Necrotic" },
    { key = "Necro02", label = "Deadflat", family = "Necrotic" },
    { key = "Necro03", label = "Crazeglaze", family = "Necrotic" },
    { key = "Necro04", label = "Charnel Ground", family = "Necrotic" },
    { key = "Necro05", label = "Marrow", family = "Necrotic" },
    { key = "Necro06", label = "Wormrot", family = "Necrotic" },
    { key = "Necro07", label = "Blightscar", family = "Necrotic" },
    { key = "Necro08", label = "Gravedust", family = "Necrotic" },
    { key = "Necro09", label = "Plaguewind", family = "Necrotic" },
    { key = "Necro10", label = "Gravebind", family = "Necrotic" },
    { key = "Void01", label = "Umbra", family = "Shadow" },
    { key = "Void02", label = "Tendril", family = "Shadow" },
    { key = "Void03", label = "Wraithsmoke", family = "Shadow" },
    { key = "Void04", label = "Eclipse", family = "Shadow" },
    { key = "Void05", label = "Whisper", family = "Shadow" },
    { key = "Void06", label = "Hollow", family = "Shadow" },
    { key = "Void07", label = "Creeping", family = "Shadow" },
    { key = "Void08", label = "Rift", family = "Shadow" },
    { key = "Void09", label = "Gloom", family = "Shadow" },
    { key = "Void10", label = "Nightfall", family = "Shadow" },
}
